services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Bind host port 80 to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount Nginx config
      - ./ui:/usr/share/nginx/html
  validate:
    build: ./validate
    expose:
      - "5001"

  login:
    build: ./login
    expose:
      - "5001"
 
  ui:
    build: ./ui
    expose:
      - "5001"
  redis:
    image: "redis"
    ports:
      - "6379:6379"
